### ISSUE TITLE
PAS laser control 'setting' button

### ISSUE THREAD

**Issue by JustinLangridge** [lo-co/exscalabar#85] opened 2016-06-10 14:52 UTC
As I it these understand 5 laser setting controls in the PAS tab are where we can change the laser power.

Currently they do not allow the user to change the values (it is always 100%)

**Comment by lo-co** [comment] 2016-06-14 05:11
Not what I am seeing.  Image below.  Closing this because I can't reproduce the problem.

![pas_setting](https://cloud.githubusercontent.com/assets/9597736/16031745/b687b6a0-31f6-11e6-8c5c-2208e1534643.png)

**Closed by lo-co** 2016-06-14 05:11 UTC
Labels: bug, invalid

**Comment by JustinLangridge** [comment] 2016-06-14 10:28
Ok this is working now. Something odd must have been happening before
